name: Deploy to S3, Invalidate CloudFront, and Publish to npm

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build

            - name: Prepare package.json for npm
              run: node prep-package.js
              shell: bash

            - name: Prepare deployment files
              run: |
                  # Read version from dist/package.json
                  VERSION=$(jq -r .version dist/package.json)
                  echo "Version: $VERSION"

                  # Create a tarball of the dist
                  TARBALL_NAME="sregdorffej-kepler-ui-$VERSION.tar.gz"
                  tar -czf $TARBALL_NAME -C dist .

                  # Create versioned folder under "v"
                  mkdir -p v/$VERSION
                  cp -r dist/* v/$VERSION/

                  # Create a deploy folder containing the latest dist, the tarball, and the v folder
                  mkdir deploy
                  cp -r dist/* deploy/  # Copy only contents of dist, not the folder itself
                  cp $TARBALL_NAME deploy/
                  cp -r v deploy/
              shell: bash

            - name: Deploy to S3 (Root Files Only)
              uses: jakejarvis/s3-sync-action@v0.5.1
              with:
                  args: --delete
              env:
                  AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  SOURCE_DIR: "deploy"
                  DEST_DIR: "" # Ensure deployment to root, not a `/` folder

            - name: Deploy to S3 (Versioned Folder)
              uses: jakejarvis/s3-sync-action@v0.5.1
              with:
                  args: "--exact-timestamps" # Ensure older versions are preserved
              env:
                  AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  SOURCE_DIR: "deploy/v"
                  DEST_DIR: "v" # Ensure deployment to /v instead of /v/

            - name: Configure AWS Credentials for CloudFront
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Create CloudFront Invalidation
              run: |
                  aws cloudfront create-invalidation \
                    --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
                    --paths "/*"

            - name: Configure npm authentication
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

            - name: Publish to npm
              run: |
                  cd dist
                  npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
